import type { GenerationPayloadMinimal, ModuleKind, ModuleNode, ModulePackage, SemanticValidationIssue } from '../../../../shared/src';
import type { HandoffArtifact } from '../../ai/handoffTypes';
import type { ProviderJob } from '../../ai/providerJobTypes';
import type { HandoffProvider } from '../../ai/providers/providerTypes';
import type { PromptBuildResult } from '../../ai/promptTypes';
import type { TransitionReadiness } from '../../packageLifecycle';
import type { Connection, DesignState, PackageSectionStatus, SectionKey } from '../../types';

export type SecondaryWorkspaceSharedProps = {
  selectedModule?: ModuleNode;
  state: DesignState;
  currentPackageContent: ModulePackage;
  transitionReadiness: TransitionReadiness | null;
  currentSectionStatuses: Record<SectionKey, PackageSectionStatus>;
  updateCurrentPackage: (updater: (current: ModulePackage) => ModulePackage) => void;
  moduleConnections: Connection[];
  generatedPayload: GenerationPayloadMinimal;
  generatedPrompt: PromptBuildResult | null;
  handoffArtifacts: HandoffArtifact[];
  latestHandoffArtifact: HandoffArtifact | null;
  approvedLeafReadyModules: ModuleNode[];
  handoffProviders: HandoffProvider[];
  selectedProviderId: string;
  setSelectedProvider: (providerId: string) => void;
  currentProviderJob: ProviderJob | null;
  copyGeneratedPrompt: () => Promise<void>;
  exportGeneratedPrompt: () => void;
  exportLatestHandoffArtifact: () => void;
  exportCurrentProject: () => void;
  importProjectFromFile: (file: File | null) => Promise<void>;
  moveToNextPackageState: () => void;
  isSelectedModuleHandoffReady: boolean;
  hasCurrentSelectedArtifact: boolean;
  moduleValidationIssues: SemanticValidationIssue[];
  designHasValidationIssues: boolean;
  isSelectedModuleValidForReviewOrHandoff: boolean;
  currentHierarchyModule?: ModuleNode;
  decompositionDraftNamesText: string;
  decompositionDraftChildKind: ModuleKind;
  setDecompositionNamesText: (value: string) => void;
  setDecompositionChildKind: (value: ModuleKind) => void;
  decomposeSelectedModule: () => void;
  selectModule: (moduleId: string) => void;
  markSelectedModuleAsHandedOff: () => void;
};
